### ISSUE TITLE
Standardize Expression / Script Parsing in BPMN, DMN

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-bpmn#11]
Standardize Expression / Script Parsing in BPMN, DMN into class(s) that can be easily overridden and whose expression syntax remains constant for decision tables, gateways, and script tasks.  Also see comments below about Python to Javascript, and removing the need for the configurator to need to know when they have to use the "model" to refer to content in the task_data.

**Comment by calexh-sar** [comment]
@w4kpm here is my swag at the top 10 FEEL expressions.

1. string length(sentence) - returns length of sentence.
2. contains(string, match) - does the string contain the match?
3. list contains(elements, element) - does elements contain the element?
4. count(list) - returns size of list.
5. all(list) - returns false if any item is false, else true if all items are true, else null.
6. any(list) - returns true if any item is true, else false if all items are false, else null.
7. append(list, item...) - returns a new list with items appended.
8. concatenate(list...) - returns a new list that is a concatenation of the arguments.
9. now() - returns the current date and time.
10. day of week(date) - returns the day of the week according to the Gregorian calendar enumeration: Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday

**Comment by danfunk** [comment]
We need to translate python to javascript in cases where the expression will be evaluated on the front end in real time.  Right now it is very difficult for a configurator to know when to use a certain syntax - issues like "True" being capitalized in Javacript and lower case in python, and "not" vs "!" and "===" vs "==" in comparison operators create a lot of confusion and issues.  We should run all of this logic through the same parser and assure that things can be consistent.  

Check the BPMN wiki to determine which tasks to translate - so that the configurators can use the same syntax whenever it needs to be handled.

hide-expression
repeat-expression
required-expression
label-expression
value-expression

**Comment by danfunk** [comment]
this is done!
